export const RoomData = [
  {
    id: 0,
    floor: 'LowFloor',
    roomType: '스탠다드',
    name: '슈페리어 더블 룸',
    bedType: '더블',
    people: '1~2명',
    roomSize: '25㎡ ~ 27㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    desc:
      '스탠다드 룸은 고객의 다양한 취향과 감각을 고려하여 각기 다른 스타일의 인테리어를 즐길 수 있도록 두 종류의 객실로 준비되어 있습니다. 안정감을 주는 베이지그레이 및 화이트 컬러를 기본으로 한 화려한 분위기의 객실과, 모던한 감각에 세련된 오리엔탈 무드를 가미한 객실 중에서 취향에 따라 선택하세요',
    roomImage: [
      { src: 'rooms/standard/superiorDouble/room1.jpg', alt: '슈페리어더블1' },
      { src: 'rooms/standard/superiorDouble/room2.jpg', alt: '슈페리어더블2' },
      { src: 'rooms/standard/superiorDouble/room3.jpg', alt: '슈페리어더블3' },
      { src: 'rooms/standard/superiorDouble/room4.jpg', alt: '슈페리어더블4' },
      { src: 'rooms/standard/superiorDouble/room5.jpg', alt: '슈페리어더블5' },
    ],
    link: 'superior-double',
    price: '120,000',
  },
  {
    id: 1,
    floor: 'LowFloor',
    roomType: '스탠다드',
    name: '슈페리어 트윈 룸',
    bedType: '더블/트윈',
    people: '2~3명',
    roomSize: '25㎡ ~ 27㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    desc:
      '스탠다드 룸은 고객의 다양한 취향과 감각을 고려하여 각기 다른 스타일의 인테리어를 즐길 수 있도록 두 종류의 객실로 준비되어 있습니다. 안정감을 주는 베이지그레이 및 화이트 컬러를 기본으로 한 화려한 분위기의 객실과, 모던한 감각에 세련된 오리엔탈 무드를 가미한 객실 중에서 취향에 따라 선택하세요.',
    roomImage: [
      { src: 'rooms/standard/superiorTwin/room1.jpg', alt: '슈페리어더트윈1' },
      { src: 'rooms/standard/superiorTwin/room2.jpg', alt: '슈페리어트윈2' },
      { src: 'rooms/standard/superiorTwin/room3.jpg', alt: '슈페리어트윈3' },
      { src: 'rooms/standard/superiorTwin/room4.jpg', alt: '슈페리어트윈4' },
    ],
    link: 'superior-twin',
    price: '130,000',
  },
  {
    id: 2,
    floor: 'HighFloor',
    roomType: '부티크',
    name: '부티크 트윈 룸',
    bedType: '더블/트윈',
    people: '2~3명',
    roomSize: '30㎡ ~ 31㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    desc:
      '부티크 트윈 룸은 모던하고 세련된 인테리어와 베이지색톤으로 쾌적하고 여유로운 공간으로 내 집 같은 편안함을 선사하는 럭셔리 트윈 룸입니다.다양한 혜택은 물론 국내 최고의 시설과 편안함을 경험해 보세요. 고객의 다양한 취향과 감각을 고려해 SOM 사, WILSON & ASSOCIATES 사, HBA 사 등 세계적인 인테리어 회사들이 디자인한 각기 다른 2가지 인테리어 스타일의 객실을 제공하고 있습니다.',
    roomImage: [
      { src: 'rooms/boutique/boutiqueTwin/room1.jpg', alt: '부티크트윈1' },
      { src: 'rooms/boutique/boutiqueTwin/room2.jpg', alt: '부티크트윈2' },
      { src: 'rooms/boutique/boutiqueTwin/room3.jpg', alt: '부티크트윈3' },
    ],
    link: 'boutique-twin',
    price: '180,000',
  },
  {
    id: 3,
    floor: 'HighFloor',
    roomType: '부티크',
    name: '부티크 패밀리 룸',
    bedType: '더블/트윈',
    people: '3~4명',
    roomSize: '32㎡ ~ 33㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    desc:
      '부티크 패밀리 룸은 고객의 다양한 취향과 감각을 고려하여 각기 다른 스타일의 인테리어를 즐길 수 있도록 두 종류의 객실로 준비되어 있습니다. 안정감을 주는 베이지그레이 및 화이트 컬러를 기본으로 한 화려한 분위기의 객실과, 모던한 감각에 세련된 오리엔탈 무드를 가미한 객실 중에서 취향에 따라 선택하세요',
    roomImage: [
      { src: 'rooms/boutique/boutiqueFamily/room1.jpg', alt: '부티크패밀리트윈1' },
      { src: 'rooms/boutique/boutiqueFamily/room2.jpg', alt: '부티크패밀리트윈2' },
      { src: 'rooms/boutique/boutiqueFamily/room3.jpg', alt: '부티크패밀리트윈3' },
      { src: 'rooms/boutique/boutiqueFamily/room4.jpg', alt: '부티크패밀리트윈4' },
    ],
    link: 'boutique-family',
    price: '210,000',
  },
  {
    id: 4,
    floor: 'HighFloor',
    roomType: '디럭스',
    name: '디럭스 트윈 룸',
    bedType: '더블/트윈',
    people: '3~4명',
    roomSize: '34㎡ ~ 35㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    desc:
      '기존 개념을 깨는 차별화된 콘셉트로 세련되게 디자인된 디럭스 트윈 룸은 고객의 다양한 취향과 감각을 고려하여 각기 다른 스타일의 인테리어를 즐길 수 있도록 2종류의 객실로 준비되어 있습니다. 안정감을 주는 베이지그레이 및 화이트 컬러를 기본으로 한 화려한 분위기의 객실과, 모던한 감각에 세련된 오리엔탈 무드를 가미한 객실 중에서 취향에 따라 선택하세요.',
    roomImage: [
      { src: 'rooms/deluxe/deluxeTwin/room1.jpg', alt: '디럭스트윈1' },
      { src: 'rooms/deluxe/deluxeTwin/room2.jpg', alt: '디럭스트윈2' },
      { src: 'rooms/deluxe/deluxeTwin/room3.jpg', alt: '디럭스트윈3' },
      { src: 'rooms/deluxe/deluxeTwin/room4.jpg', alt: '디럭스트윈4' },
    ],
    link: 'deluxe-twin',
    price: '220,000',
  },
  {
    id: 5,
    floor: 'HighFloor',
    roomType: '디럭스',
    name: '디럭스 스위트 룸',
    bedType: '더블/트윈',
    people: '3~4명',
    roomSize: '35㎡ ~ 37㎡',
    checkInOutTime: '15시/12시',
    view: '시티',
    desc:
      '기존 개념을 깨는 차별화된 콘셉트로 세련되게 디자인된 디럭스 스위트 룸은 동급 객실보다 더넓은 느낌의 객실입니다.고객의 다양한 취향과 감각을 고려하여 각기 다른 스타일의 인테리어를 즐길 수 있도록 2종류의 객실로 준비되어 있습니다. 안정감을 주는 베이지그레이 및 화이트 컬러를 기본으로 한 화려한 분위기의 객실과, 모던한 감각에 세련된 오리엔탈 무드를 가미한 객실 중에서 취향에 따라 선택하세요.',
    roomImage: [
      { src: 'rooms/deluxe/deluxeSuite/room1.jpg', alt: '디럭스스위트1' },
      { src: 'rooms/deluxe/deluxeSuite/room2.jpg', alt: '디럭스스위트2' },
      { src: 'rooms/deluxe/deluxeSuite/room3.jpg', alt: '디럭스스위트3' },
      { src: 'rooms/deluxe/deluxeSuite/room4.jpg', alt: '디럭스스위트4' },
      { src: 'rooms/deluxe/deluxeSuite/room5.jpg', alt: '디럭스스위트5' },
    ],
    link: 'deluxe-suite',
    price: '240,000',
  },
  {
    id: 6,
    floor: 'HighFloor',
    roomType: '스위트',
    name: '스위트 프리미어 룸',
    bedType: '더블/트윈',
    people: '4~6명',
    roomSize: '40㎡ ~ 43㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    desc:
      '최고 수준의 우아함, 섬세함, 럭셔리함과 함께, 롯데호텔만의 최상의 서비스를 경험할 수 있는 프리미어 스위트룸은 최고급 가구만을 갖추었습니다. 대형 유리창을 통해 서울 시내를 한 눈에 내려다 볼 수 있으며 당신의 모든 빛나는 순간을 함께 합니다.',
    roomImage: [
      { src: 'rooms/suite/suitePremier/room1.jpg', alt: '스위트프리미어1' },
      { src: 'rooms/suite/suitePremier/room2.jpg', alt: '스위트프리미어2' },
      { src: 'rooms/suite/suitePremier/room3.jpg', alt: '스위트프리미어3' },
      { src: 'rooms/suite/suitePremier/room4.jpg', alt: '스위트프리미어4' },
    ],
    link: 'suite-premier',
    price: '300,000',
  },
  {
    id: 7,
    floor: 'HighFloor',
    roomType: '스위트',
    name: '로얄 스위트 룸',
    bedType: '더블/트윈',
    people: '2~3명',
    roomSize: '42㎡ ~ 45㎡',
    view: '시티',
    checkInOutTime: '15시/12시',
    desc:
      '로얄스위트는 국내외 VIP만을 위하여 준비된 저희 호텔을 대표하는 명실상부 최고의 객실입니다. 최상의 서비스를 제공하며 호텔 그 이상의 가치를 추구합니다.',
    roomImage: [
      { src: 'rooms/suite/royalSuite/room1.jpg', alt: '로얄스위트1' },
      { src: 'rooms/suite/royalSuite/room2.jpg', alt: '로얄스위트2' },
      { src: 'rooms/suite/royalSuite/room3.jpg', alt: '로얄스위트3' },
      { src: 'rooms/suite/royalSuite/room4.jpg', alt: '로얄스위트4' },
    ],
    link: 'royal-suite',
    price: '320,000',
  },
];
